algoritmo "Media"

var
      nome: caractere
      valor:  real

inicio
      escreva ("Digite o seu nome: ")
      leia(nome)
      escreva ("Digite o seu salário: ")
      leia(valor)
      

      Escreval( " Nome do Funcionário: " , nome )
      Escreval( " Salário do Funcionário: " , valor)
      Escreval ( " O funcionário " , nome, " tem um salário de" , valor , " reais em Junho." )

fimalgoritmo
